### ISSUE TITLE
This library is awesome and it does exactly what I need, but I have one problem.

### ISSUE THREAD

**Issue by MajickTek** [Pyratron/Command-Parser#8]
I need to be able to have a string as an argument. Probably surrounded by quotes.

If I have a command:
~~~~
type “Hello, World!” 100
~~~~

It takes everything after the comma as the second argument, when I just want 100 to be argument 2.

Is there any way to implement this in the library? Or would it require rewriting the entire thing?

**Comment by Cyral** [comment]
Hi,

I haven't worked on this library in forever so I am not actually sure if this is supported, but reading the code it looks like it should be:

https://github.com/Pyratron/Command-Parser/blob/master/DotNET/Parser/CommandParser.cs#L162
"//Split the string into arguments ignoring spaces between quotes."

It could be that you are using those curly quotes instead of regular quotes. (Use " instead of “)

If you must support those quotes you can modify the regex to include them on the line I linked to.

**Comment by MajickTek** [comment]
Thanks for replying! I’m using the Java version so I don’t know if there are any differences regarding features.

**Comment by MajickTek** [comment]
It looks the same actually so I guess I can look into the regex and see why it’s not working for me. Thanks!

Edit: In case anyone reads this, my issue was that i added the number argument as a nested argument to the string argument.
So I just had to separate them.
~~~~Java
.addArgument(Argument.create("message").addArgument(Argument.create("delay").setValidator(ValidationRule.Integer)))
~~~~

became

~~~~Java
.addArgument(Argument.create("message"))
				.addArgument(Argument.create("delay").setValidator(ValidationRule.Integer))
~~~~
